version: '3.8'
services:
  db:
    image: postgres:16.8
    environment:
      POSTGRES_DB: productsapi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: banco123
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
